### ISSUE TITLE
BrightBox Provider Review

### ISSUE THREAD

**Issue by mbfrahry** [brightbox/terraform-provider-brightbox-old#3]
Hello! My name is Matthew and I'm on the Terraform team at Hashicorp. I've taken the time to go over your provider and would like to provide feedback on what needs doing before we can move this provider under the terraform-providers organization. 

There is a quite a bit here but I do want to say that the provider looks good for the most part. I'd just say that the main thing is around readability of the provider. When providers look the similar, it makes it very easy to jump from provider to provider and have minimal context switching when doing so. But we also understand that there are certain design limitations when building a provider so if there is a point that I'm making that just doesn't make sense for your provider than please call it out and I'm sure we can work something out. Without further ado, here is the list. It's somewhat ranked with higher priority things at the top and more questions about the design at the bottom. Thanks!

- [x] I'm curious to know about the setAttributes function. At the end of the Create/Update methods, we just like to call the Read function. If you do that, you can get rid of the setAttributes function entirely. https://github.com/brightbox/terraform-provider-brightbox/blob/master/brightbox/resource_brightbox_cloudip.go#L94

- [x] In the same vein, if there is an attribute to update after creating the resource, you can just call the update method. For example, instead of calling assignTargetIP in the create method, you can just return the update method which will assign the target ip if applicable. 
setAttribute() can be kept in the read function https://github.com/brightbox/terraform-provider-brightbox/blob/master/brightbox/resource_brightbox_cloudip.go#L188
removeCloudIP can be left in the delete function https://github.com/brightbox/terraform-provider-brightbox/blob/master/brightbox/resource_brightbox_cloudip.go#L230

- [x] It looks like we can get rid of some LoC. This function (https://github.com/brightbox/terraform-provider-brightbox/blob/master/brightbox/resource_brightbox_cloudip.go#L109) just calls WaitForCloudIP. Is there a reason we can't just call WaitForCloudIP instead of WaitForMapped?

- [ ] https://github.com/brightbox/terraform-provider-brightbox/blob/master/brightbox/resource_brightbox_cloudip.go#L167 “mapped” and “unmapped” should be constants at the top of the file. This is useful if for whatever reason the values change for the api and we only need to update them in one place as opposed to finding and potentially missing them in multiple places. This happens more often than it should 

- [ ] In the tests, https://github.com/brightbox/terraform-provider-brightbox/blob/master/brightbox/resource_brightbox_cloudip_test.go#L50 and https://github.com/brightbox/terraform-provider-brightbox/blob/master/brightbox/resource_brightbox_cloudip_test.go#L51 look to be doing the same thing (checking the cloud ip name). We can get rid of line and just check it the standard way in line 51

- [ ] There is a check for if there is more than one HealthCheck specified for the loadbalancer resource. Instead you can just set MaxItems: 1 in the schema [here] (https://github.com/brightbox/terraform-provider-brightbox/blob/master/brightbox/resource_brightbox_load_balancer.go#L101)

- [ ] The Read function should be returned here https://github.com/brightbox/terraform-provider-brightbox/blob/master/brightbox/resource_brightbox_container.go#L118
https://github.com/brightbox/terraform-provider-brightbox/blob/master/brightbox/resource

- [ ] The fmting seems a little off in areas as well. If you run `gofmt -s -w` that’ll fix it up to be in line with golang’s standard format

- [ ] For each resource that is importable, we should have a corresponding import test for each resource test

- [ ] I’m curious to know why double pointers are being used [here] (https://github.com/brightbox/terraform-provider-brightbox/blob/master/brightbox/structure.go). Is there a way that we can make this simpler? 

- [ ] A lot of the attributes default to nil. https://github.com/brightbox/terraform-provider-brightbox/blob/master/brightbox/resource_brightbox_database_server.go#L65. I'm curious about the rationale behind that. If you remove `Default: nil` and request that attribute when nothing is specified, nil should be returned.

- [ ] There are some resources where every attribute is optional. So I could have a resource block that looks like 
```
resource "brightbox_database_server" "default" {
}
``` 
with no attributes specified. I'm curious to know whether this resource will actually be created? This could work but it seems odd that it would

**Comment by NeilW** [comment]
Thanks for the note, and apologies for not getting onto this as quickly as I would normally do so. Notifications failed to arrive. I've fixed that and it shouldn't happen again. 

I'll look into your points today. I've already checked the formatting issue you raise, and I'm struggling to see what the issue is. The code passes `make fmtcheck` and the script it calls is the same one called in quite a few of the other terraform providers. Similarly `make fmt` makes no changes to the code at all.

So the code appears to be formatted according to the automated requirements in the make system. If those aren't correct, shouldn't they be changed in the automated system, and then they will be applied everywhere consistently?

**Comment by NeilW** [comment]
Brightbox will create resources using sensible defaults if requested. Exactly the same happens on our cloud manager, where you can hit one button and get a database built to sensible defaults.

The database server resource you quote above will get you a 2GB SSD MySQL 5.6 database with daily snapshots to Cloud storage.

**Comment by NeilW** [comment]
Thank you for you comments Matthew and the time taken to review the
provider. I appreciate it.

I've looked at your comments, updated the code and released v1.04 with the updates.
In answer to your comments:

1. `setServerAttributes` is there to avoid an additional cycle via
the Brightbox API. We designed our Api to return the updated structure
(including applied backend defaults) as part of create and update within
a single API call, and we would like to take advantage of that.

2. As 1.

3. With `waitForMapped` I'm adding some semantic value to an abstract
function. It costs some extra lines of code but gives a lot more
information about what it does than `waitForCloudip`. It's just the
usual function currying technique.

4. Fixed and applied

5. Fixed and applied

6. Fixed and applied

7. Refactored

8. I've run the reformat as suggested, however as mentioned the code
did conform to the fmtcheck.sh used across all the other providers. If
that isn't producing the correct format it should really be changed in
the script and applied globally.

9. As far as I can see all the resources that are importable have an
import test. Was there one in particular where I've missed it out?

10. The double pointer is there because it is a setter function for
a pointer. We use pointers to strings in the API because `""` has a
different meaning from `nil`. The same with the other types.

11. nil defaults stripped and applied

12. As mentioned Brightbox Cloud resources are opinionated and have
sensible, documented defaults. :-)

**Comment by mbfrahry** [comment]
Hey @NeilW. Just finished looking over your changes and they look good! There are just a couple more things to note but I don't think they'll hinder us from moving forward, just more things to consider.

You're right that every resource that is importable has an import test. It's best practice though, that for every resource test, there is also an import test. For example, there are quite a few tests [here](https://github.com/brightbox/terraform-provider-brightbox/blob/master/brightbox/resource_brightbox_server_test.go). It'd be best if each of those tests also had an import test to make sure everything gets imported correctly. 

Many providers in Terraform like to use `Default: "value"` when the api defaults an attribute.  You're using `Computed: true` which works but isn't best practice. I'll leave you to decide which is best but for areas that are defaulted by the API, let's make sure that `Computed: true` is marked for those attributes in the schema. For example, everything is Optional [here](https://github.com/brightbox/terraform-provider-brightbox/blob/master/brightbox/resource_brightbox_firewall_policy.go). Should we set `Computed: true` so these attributes are tracked in the state file?

We should clean up some of the extra files in the provider as well. Can you remove [install.sh](https://github.com/brightbox/terraform-provider-brightbox/blob/master/install.sh), [Jenkinsfile](https://github.com/brightbox/terraform-provider-brightbox/blob/master/Jenkinsfile), [tagrelease.sh](https://github.com/brightbox/terraform-provider-brightbox/blob/master/tagrelease.sh), etc. Are these files necessary or just ones that helped maintain the provider?

**Comment by NeilW** [comment]
I've added in the extra import tests into each test file to cover all the different configs tested in there. I've run through the resources and everything that is defaulted by the API to a non-empty value is already set to `Computed: true`. You asked in the last message to remove `Default: nil` from attributes that defaulted to empty. That is what these Optional attributes are doing - defaulting to empty.

I've cleaned up the files on the master branch, and re-synced the Makefile and travis file to the standard.

**Comment by mbfrahry** [comment]
Are they defaulting to nil though? From your previous comment, when you submit an empty database resource, the values are defaulting to 2GB SSD MySQL 5.6 database with daily snapshots to Cloud storage. In the schema declaration, we can default those attributes to what the api will create when nothing is submitted.

**Comment by NeilW** [comment]
Yes, and all those attributes on database that are set by the API to non-empty are `Computed: true`. The ones that are empty, stay empty. Have you got a specific case where I've got this wrong?

**Comment by mbfrahry** [comment]
It comes down to the behavior of  
```
Optional: true,
Computed: true,
```
We can take [database_server](https://github.com/brightbox/terraform-provider-brightbox/blob/master/brightbox/resource_brightbox_server.go#L67) as an example. Say we have this resource block 
```
resource "brightbox_database_server" "example" {
  name = "example server"
  server_groups = ["example", "server", "groups"]
}
```
This will create a server associated with those server groups, but say we don't want those server groups associated with that server any more. You'd modify that resource block to look like 
```
resource "brightbox_database_server" "example" {
  name = "example server"
}
```
However, Terraform won't remove the server_groups because of how `Computed` works. Terraform sees that server_groups are associated with the server and that satisfies the `Computed` piece. It's a little confusing but this will be true for everywhere that you use 
```
Optional: true,
Computed: true,
```

**Comment by NeilW** [comment]
That's brightbox server, not database server, which is where the confusion is coming in.  That attribute follows the model of the vpc_security_group_ids from the AWS provider.

Is there a better example where only 'Optional' works?

**Comment by NeilW** [comment]
I've updated both the server_groups and allow_access Sets so that the require at least one entry, and added a server group data source to make picking up the default server group easier. The API does support zero length lists, but the decoupling use case that permits doesn't make a lot of sense in a Terraform context.
